[package]
authors = ['Substrate DevHub <https://github.com/substrate-developer-hub>']
description = 'FRAME pallet template for defining custom runtime logic.'
edition = '2018'
homepage = 'https://substrate.dev'
license = 'Unlicense'
name = 'pallet-standard-oracle'
repository = 'https://github.com/substrate-developer-hub/substrate-node-template/'
version = '2.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']


[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.119'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.0.0'

[dependencies]
frame-support =  {  default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
sp-runtime = {  default-features = false, version = '3.0.0' }
sp-core = { default-features = false, version = '3.0.0' }
sp-std = { default-features = false, version = '3.0.0' }
#pallet-balances = { git = "https://github.com/paritytech/substrate",  default-features = false, version = '3.0.0' }
#pallet-chainlink = {default_features = false, git = 'https://github.com/smartcontractkit/chainlink-polkadot.git' }
primitives = { path = "../../primitives", default-features=false }

[dev-dependencies]
sp-core = {  default-features = false, version = '3.0.0' }
sp-io = {  default-features = false, version = '3.0.0' }

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-core/std',
    'sp-std/std',
    'primitives/std',
]
